<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="Addtocartpage.aspx.vb" Inherits="finalassesmentproject.Addtocartpage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        #modifytable {
            height: 223px;
            width: 554px;
            border:solid;
            border-color:black;
        
           
        }
        #gvdiv{
  margin-left:250px;
        }

    </style>
    <script>
function script2()
  {
  return confirm('This will Remove All Your Cart Items?');
  }
</script>
</head>
<body style="background-color:beige">
    <form id="form1" runat="server">
    <div id="gvdiv">
        <asp:MultiView ID="MultiView1" runat="server">
            <asp:View ID="View1" runat="server">
        <table  style="width: 545px">
            <tr>
                <td style="text-align: center">
 <asp:LinkButton ID="viewcartbutton" runat="server" Text="View cart" style="text-align: center"></asp:LinkButton>
                </td>
                <td style="text-align: center">
 <asp:HyperLink ID="HyperLink1" runat="server" Text="Continue Shopping" NavigateUrl="~/userloginhomepage.aspx"></asp:HyperLink>
                </td>
                <td style="text-align: center">
                     <asp:LinkButton ID="clearcartbutton" runat="server" Text="Clear Cart" ForeColor="Red" OnClientClick="return script2()"></asp:LinkButton>
                </td>
            </tr>
        </table>
       
       
        <asp:GridView ID="gvlogincart" runat="server" AutoGenerateColumns="False" Height="265px" Width="526px" AutoGenerateDeleteButton="True" DataKeyNames="userid" BackColor="White" BorderColor="#E7E7FF" BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Horizontal" ShowFooter="True">
            <AlternatingRowStyle BackColor="#F7F7F7" />
            <Columns>             
                <asp:BoundField DataField="userid" HeaderText="Product ID" />
                <asp:BoundField DataField="product_name" HeaderText="Product Name" />
                <asp:TemplateField HeaderText="Product Image">
                    <ItemTemplate>
                        <asp:Image ID="Image1" runat="server" height ="100px" Width ="90px" ImageUrl='<%# Eval("product_image") %>'/>
                    </ItemTemplate>
                    <ItemStyle HorizontalAlign="Center" />
                </asp:TemplateField>
                <asp:BoundField DataField="quantity" HeaderText="Qauntity" />
                <asp:BoundField DataField="product_price" HeaderText="Price" />
                <asp:BoundField DataField="Total_Price" HeaderText="Total Price" />
                            
                         <asp:TemplateField HeaderText="Modify Products">
                             <ItemTemplate>
                                 <asp:LinkButton ID="LinkButton1" runat="server" Text="Modify" CommandName="Select"></asp:LinkButton>
                             </ItemTemplate>
                         </asp:TemplateField>   
           </Columns>

            <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" Font-Bold="True" Font-Underline="True" HorizontalAlign="Center" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
            <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
            <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
            <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
            <SortedAscendingCellStyle BackColor="#F4F4FD" />
            <SortedAscendingHeaderStyle BackColor="#5A4C9D" />
            <SortedDescendingCellStyle BackColor="#D8D8F0" />
            <SortedDescendingHeaderStyle BackColor="#3E3277" />

        </asp:GridView> 
                </asp:View> 
        <asp:View ID="View2" runat="server">

            <table id="modifytable">
                <tr>
                    <td>
                        Product Name
                    </td>
                    <td>
                        <asp:TextBox ID="txtproductname" runat="server" Height="27px" Width="290px" BackColor="#CCCCCC" Font-Bold="True" ReadOnly="True"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                       Price
                    </td>
                    <td>
                        <asp:TextBox ID="txtprice" runat="server"  Height="27px" Width="290px" BackColor="#CCCCCC" Font-Bold="True" ReadOnly="True"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                       Quantity
                    </td>
                    <td>
                        <asp:TextBox ID="txtquantity" runat="server"  Height="27px" Width="290px" Font-Bold="True" TextMode="Number"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td style="text-align: center">
                        <asp:LinkButton ID="updatebutton" runat="server" Text="Update"></asp:LinkButton>                                            
                    </td>
                    <td>
                         <asp:TextBox ID="txtuserid" runat="server" Visible="False"></asp:TextBox>
                    </td>
                </tr>
            </table>
            </asp:View>
             </asp:MultiView>
        </div>          
    </form>  
</body>

</html>
