<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="Adminpage.aspx.vb" Inherits="finalassesmentproject.Adminpage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style>
        #admintable {
            border: solid;
            border-color: rosybrown;
            text-align: center;
            margin-left:400px;
            
        }
    </style>
</head>
<body style="background-color:honeydew">
    <form id="form1" runat="server">
    <div>
    <asp:MultiView ID="MultiViewadmin" runat="server">
                <asp:View ID="View1" runat="server">
                    <table id="admintable">
                        <tr>
                            <td colspan="3">
                                <asp:Image ID="Image1" runat="server" Height="92px" ImageUrl="~/Logo Image/admin logo.jfif" Width="118px" />
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3"><b>Admin Login</b></td>
                        </tr>
                        <tr>
                            <td>UserName</td>
                            <td>
                                <asp:TextBox ID="txtadminname" runat="server"></asp:TextBox></td>
                            <td>
                                <asp:Label ID="lbladminname" runat="server" ForeColor="Red"></asp:Label>
                            </td>
                        </tr>
                        <tr>
                            <td>Password</td>
                            <td>
                                <asp:TextBox ID="txtadminpassword" runat="server" TextMode="Password"></asp:TextBox>
                            </td>
                            <td>
                                <asp:Label ID="lbladminpass" runat="server" ForeColor="Red"></asp:Label></td>

                        </tr>
                        <tr>
                            <td>
                                <asp:Button ID="adminloginbutton" runat="server" Text="Login" Width="61px" OnClick="adminloginbutton_Click" />

                            </td>
                            <td>
                                <asp:Button ID="adminlogoutbutton" runat="server" Text="Home" OnClick="adminlogoutbutton_Click" /></td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <asp:Label ID="lbladmin" runat="server"></asp:Label>
                            </td>
                        </tr>
                    </table>
                </asp:View>
                <asp:View ID="View2" runat="server">
                    Select catogory:<asp:DropDownList ID="ddladminsorting" runat="server" DataValueField="catogory_id" DataTextField="catogory_name" AutoPostBack="True" Width="162px">
                        <asp:ListItem Text="--Select--" Value="0"></asp:ListItem>
                        <asp:ListItem Text="Mobile" Value="1"></asp:ListItem>
                        <asp:ListItem Text="perfumes" Value="2"></asp:ListItem>
                        <asp:ListItem Text="Bags" Value="3"></asp:ListItem>
                    </asp:DropDownList>
                    <asp:GridView ID="gvadmin" runat="server" AutoGenerateColumns="False" DataKeyNames="product_id" AutoGenerateDeleteButton="True" OnRowDeleting="gvadmin_RowDeleting" OnRowDataBound="onrowdatabound" OnSelectedIndexChanged="gvadmin_SelectedIndexChanged" Height="238px" Width="750px" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Vertical">
                        <AlternatingRowStyle BackColor="#DCDCDC" />
                        <Columns>
                            <asp:TemplateField HeaderText="UpdateProducts">
                                <ItemTemplate>
                                    <asp:LinkButton Text="Edit" ID="lnkSelect" runat="server" CommandName="Select" />
                                </ItemTemplate>
                                <ItemStyle HorizontalAlign="Center" />
                            </asp:TemplateField>
                            <asp:BoundField DataField="product_id" HeaderText="Product ID" >
                            <ItemStyle HorizontalAlign="Center" />
                            </asp:BoundField>
                            <asp:BoundField DataField="product_name" HeaderText="Product Name" >
                            <ItemStyle HorizontalAlign="Center" />
                            </asp:BoundField>
                            <asp:BoundField DataField="product_price" HeaderText="Price in Rupees" >
                            <ItemStyle HorizontalAlign="Center" />
                            </asp:BoundField>
                            <asp:TemplateField HeaderText="Image">
            <ItemTemplate>
                <asp:Image ID="Image1" runat="server" height ="100px" Width ="90px" ImageUrl='<%# Eval("product_image") %>'/>
            </ItemTemplate>
                                <ItemStyle HorizontalAlign="Center" />
        </asp:TemplateField>
                        </Columns>
                        <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
                        <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                        <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
                        <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                        <SortedAscendingHeaderStyle BackColor="#0000A9" />
                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                        <SortedDescendingHeaderStyle BackColor="#000065" />
                    </asp:GridView>
                    <asp:TextBox ID="txtproductnameupdate" runat="server" Width="217px"></asp:TextBox>
                    <asp:TextBox ID="txtpriceupdate" runat="server" TextMode="Number" Width="217px"></asp:TextBox>
                    <%--<asp:RegularExpressionValidator ID="RegularExpressionValidatornumber" runat="server" ErrorMessage="Only Number allowed" ForeColor="Red" ControlToValidate="txtpriceupdate" Display="Dynamic"></asp:RegularExpressionValidator>--%>
                    <asp:Button ID="priceupdatebutton" runat="server" Text="Update" OnClick="priceupdatebutton_Click" Width="103px" />
                    <asp:TextBox ID="txtproductidinvisible" runat="server" ReadOnly="True" Visible="False"></asp:TextBox>
                    <br />
                    <asp:Button ID="logoutbutton" runat="server" Text="Logout"  />
                    <asp:Button ID="AddNewProductbutton" runat="server" Text="Add New Product" OnClick="AddNewProductbutton_Click" />
                    <asp:Label ID="lbladmindbstatus" runat="server" Font-Size="Large"></asp:Label>
                </asp:View>
                <asp:View ID="View3" runat="server">
                    Product Category
                    <asp:DropDownList ID="ddladdproduct" runat="server"
                        DataValueField="catogory_id" DataTextField="catogory_name">

                        <asp:ListItem Text="Select" Value="0"></asp:ListItem>
                        <asp:ListItem Text="Mobile" Value="1"></asp:ListItem>
                        <asp:ListItem Text="perfumes" Value="2"></asp:ListItem>
                        <asp:ListItem Text="Bags" Value="3"></asp:ListItem>

                    </asp:DropDownList>
                    Product Name:<asp:TextBox ID="txtproductname" runat="server"></asp:TextBox>
                    Product Price:<asp:TextBox ID="txtproductprice" runat="server"></asp:TextBox>
                    <br />
                    <br />
                    <asp:Image ID="Image2" runat="server" BackColor="White" Height="104px" ImageUrl="~/Logo Image/new product logo.jfif" Width="168px" />
                    <asp:FileUpload ID="FileUpload1" runat="server" />
                    <br />
                    <asp:Button ID="insertbutton" runat="server" Text="Add product" OnClick="insertbutton_Click" />
                    <asp:Button ID="Backbutton" runat="server" Text="Back" OnClick="Backbutton_Click" />
                    <br />
                    <asp:Label ID="lbladdproduct" runat="server" Font-Size="Large"></asp:Label>
                    <br />
                    <asp:Label ID="lblimage" runat="server"></asp:Label>
                </asp:View>

            </asp:MultiView>
    </div>
    </form>
</body>
</html>
